"""final

Revision ID: 3f5415eea2a8
Revises: 661fa6fcd8f4
Create Date: 2026-01-23 20:50:42.852034

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3f5415eea2a8"
down_revision: Union[str, Sequence[str], None] = "661fa6fcd8f4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("urls")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "urls",
        sa.Column("short_code", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("long_url", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column("access_count", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("short_code", name=op.f("urls_pkey")),
    )
    # ### end Alembic commands ###
