"""empty message

Revision ID: 661fa6fcd8f4
Revises:
Create Date: 2026-01-18 21:23:59.168982

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "661fa6fcd8f4"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "urls",
        sa.Column("short_code", sa.String(), nullable=False),
        sa.Column("long_url", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("access_count", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("short_code"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("urls")
    # ### end Alembic commands ###
