"""final2

Revision ID: 72e8db78b7cb
Revises: 3f5415eea2a8
Create Date: 2026-01-23 21:00:03.217339

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "72e8db78b7cb"
down_revision: Union[str, Sequence[str], None] = "3f5415eea2a8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
